package ludo;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.NoSuchElementException;
import java.util.Random;
import java.util.Scanner;
import javax.imageio.ImageIO;
import static javax.swing.JOptionPane.showInputDialog;
import static ludo.ImgPath.DICE_PATH;
import static ludo.ImgPath.FILE_EXTENSION;
import static ludo.LudoGUI.TILE_SIZE;

/**
 * Represents a regular dice with 6 possible outcomes.
 * This object contains the following information:
 * <ul>
 * <li>The result obtained after casting the dice
 * <li>Whether the dice results are being generated randomly or by user input
 * <li>The player that is currently holding the dice
 * <li>The number of times the dice has been casted at any given moment
 * <li>The images to represent this object in the GUI
 * </ul>
 * <p>
 * 
 * @author Carla Villegas <carv@itu.dk>
 */
public class Dice{

    public static final int DICE_SIZE=(int)(1.5*TILE_SIZE);
    private final Random random = new Random();
    private Scanner scanner;
    private final int ACC=0;
    private int result = 3;
    private int pIndex; //player holding the dice
    private boolean isSix = false,
                    animated = false,
                    debug = false;
    private int[] coordinates = new int[2];
    private int tickCounter;
    private int pos, vel;
    private int diceRollCount;
    
    private BufferedImage dice[] = new BufferedImage[6];
    private BufferedImage diceAnimation[] = new BufferedImage[25];
    private BufferedImage diceImg;
  
    /**
     * Initializes an instance of Dice.
     */
        public Dice(){  
        try {
            for (int i=0; i<dice.length; i++) 
                    dice[i]=ImageIO.read(new File(DICE_PATH+"result"+(i+1)+FILE_EXTENSION));
            for (int i=0; i<diceAnimation.length; i++) 
                    diceAnimation[i]=ImageIO.read(new File(DICE_PATH+"animateddice"+(i+1)+FILE_EXTENSION));}
        catch (IOException ex) {
                System.out.println("Image not found.");}
        diceImg = dice[result-1];
        this.coordinates[0]=(TILE_SIZE*15-DICE_SIZE)/2;
        this.coordinates[1]=(TILE_SIZE*15-DICE_SIZE)/2;
    }
    
    /**
     * Gets the integer number in the range [1-6] obtained after casting the dice.
     * @return the outcome after a dice roll in the range [1-6].
     */
    public int getResult() {
        return this.result;
    }
    
    /**
     * Sets the dice result to a given number.
     */
    public void setResult(int result) {
        this.result = result;
        this.isSix = this.result == 6;
    }
    
    /**
     * Represents the number of times the dice has been casted during a game.
     * @return the count of total dice-casts
     */
    public int getDiceRollCount() {
        return this.diceRollCount;
    }

    /**
     * Gets a new dice result by the same player/holder.
     */
    public void reRoll() {
        this.result = this.roll();
        this.isSix = this.result == 6;
    }

    /**
     * Gets the index of the player currently holding the dice.
     * @return int number [0-3] representing the index of the player holding the dice
     */
    public int getHolder() {
        return this.pIndex;
    }

    /**
     * Hands the dice to the player with the given index.
     * @param pIndex int number [0-3] representing the index of the player receiving the dice
     */
    public void setHolder(int pIndex) {
        this.pIndex = pIndex;
    }

    /**
     * Indicates whether the dice result is six.
     * @return true if the dice result is six, false otherwise
     */
    public boolean getIsSix() {
        return this.isSix;
    }
    
    /**
     * Simulates that a dice result is equal to six or not equal to six.
     * This method is meant to be used for testing/debugging purposes.
     * @param isSix true if the dice result should simulate a six, false if it simulates any other outcome
     */
    public void setIsSix(boolean isSix) {
        this.isSix = isSix;
    }
    
    /**
     * Indicates whether the dice results are being generated randomly or by user input.
     * @return true if the dice results are generated by user input, false if the results are random
     */
    public boolean getDebug() {
        return this.debug;
    }
    
    /**
     * Switches debug mode on/off.
     * @param debug true for user generated dice results, false for random results
     */
    public void setDebug(boolean debug) {
        this.debug = debug;
    }

    /**
     * Gets the coordinates of the dice in the GUI frame.
     * @param i 0 to retrieve x-coordinate, 1 to retrieve y-coordinate
     * @return the position of the dice in pixels (x or y coordinate) in the GUI frame
     */
    public int getCoordinates(int i) {
        return this.coordinates[i];
    }
    
     /**
     * Gets the graphic representation of the dice at any given moment.
     * @return the image used to represent the dice in the GUI
     */
    public BufferedImage getDiceImg() {
        return this.diceImg;
    }
    
    /**
     * The player with index pIndex rolls the dice.
     * @param pIndex number [0-3] representing the index of the player that will cast the dice
     */
    public void rollDice(int pIndex) {
        this.pIndex = pIndex;
        this.result = this.roll();
        this.isSix = this.result == 6;
        resetCoordinates();
        this.tickCounter=0;
        this.vel=1;
        this.diceRollCount++;
    }

    /**
     * Generates a dice result.
     * In debug mode the result is generated by user input, else it is randomly generated.
     * @return the outcome or a dice roll in the range [1-6].
     */
    public int roll() {
        if(!debug)
            this.result = random.nextInt(6) + 1;
        else{
            scanner = new Scanner(showInputDialog("Enter dice value (1-6):"));
            try{int res = scanner.nextInt()%7;
                this.result = res!=0? res:6;
            }
            catch(NoSuchElementException ne){this.result=6;}     
            }
        return this.result;
    }
    
    /**
     * Sets the dice coordinates to the corner of the player holding the dice.
     */
    public void resetCoordinates(){
        pos=0;
        if(this.pIndex<2){
            this.coordinates[0]=TILE_SIZE*15-DICE_SIZE;}
        else{
            this.coordinates[0]=0;}
        if(this.pIndex%3==0){
            this.coordinates[1]=0;}
        else{
            this.coordinates[1]=TILE_SIZE*15-DICE_SIZE;}   
    }
    
    /**
     * Set coordinates x and y to a given position.
     * In this case, the coordinates x and y will have the same value.
     * @param pos the position in the frame, in pixels
     */
    public void setCoordinates(int pos){
        if(this.pIndex<2){
            this.coordinates[0]=TILE_SIZE*15-DICE_SIZE-pos;}
        else{
            this.coordinates[0]=pos;}
        if(this.pIndex%3==0){
            this.coordinates[1]=pos;}
        else{
            this.coordinates[1]=TILE_SIZE*15-DICE_SIZE-pos;}
    }

    /**
     * Select a new image to represent the dice with every tick of the timer that controls the dice animation from the GUI.
     */
    public void animateDice() {
        pos += vel*tickCounter + ACC*tickCounter*tickCounter/2;
        if(pos<(TILE_SIZE*15-DICE_SIZE)/2){
            if(this.pIndex%3==0)
                diceImg = diceAnimation[tickCounter%diceAnimation.length];
            else
                diceImg = diceAnimation[diceAnimation.length-1-(tickCounter%diceAnimation.length)];
            tickCounter++;
            vel += ACC;}
        else{
            diceImg = dice[result-1];
            pos=(TILE_SIZE*15-DICE_SIZE)/2;}
        setCoordinates(pos);
        //System.out.println("dice pos "+pos);
    }
}
    
